[asusctl]
src.aur = 'asusctl'
fetch.git = 'https://gitlab.com/asus-linux/asusctl'
cargo_locks = [ 'Cargo.lock' ]

[notify-rust]
src.git = 'https://github.com/flukejones/notify-rust.git'
fetch.github = 'flukejones/notify-rust'

[fcitx5-nord]
src.git = 'https://github.com/tonyfettes/fcitx5-nord.git'
fetch.github = 'tonyfettes/fcitx5-nord'

[snack]
src.webpage = 'https://www.speech.kth.se/snack/'
src.regex = 'Snack v[0-9]+\.[0-9]+\.[0-9]+'
src.prefix = 'Snack v'
fetch.url = 'http://www.speech.kth.se/snack/dist/snack$ver.tar.gz'

[supergfxctl]
src.aur = 'supergfxctl'
fetch.git = 'https://gitlab.com/asus-linux/supergfxctl'
cargo_locks = [ 'Cargo.lock' ]

[wavesurfer]
src.httpheader = 'http://downloads.sourceforge.net/wavesurfer/wavesurfer-1.8.8p5-src.tgz'
src.regex = '[0-9]+.[0-9]+.[0-9]+p[0-9]+'
fetch.url = 'http://downloads.sourceforge.net/wavesurfer/wavesurfer-$ver-src.tgz'

[droidcam-obs-plugin]
src.aur = 'droidcam-obs-plugin'
src.branch = '$ver'
fetch.git = 'https://github.com/dev47apps/droidcam-obs-plugin'

[xp-pen-tablet]
src.aur = 'xp-pen-tablet'
fetch.url = 'https://www.xp-pen.com/download/file/id/1936/pid/690/ext/gz.html'

[knp]
src.git = 'https://github.com/ku-nlp/knp/'
fetch.github = 'ku-nlp/knp'

# python modules
[doq]
src.pypi = 'doq'
fetch.pypi = 'doq'

[pyknp]
src.pypi = 'pyknp'
fetch.pypi = 'pyknp'

