[asusctl]
src.aur = 'asusctl'
src.branch = '$ver'
fetch.git = 'https://gitlab.com/asus-linux/asusctl'

[egui]
src.github_tag = "emilk/egui"
src.include_regex = '[0-9]+\.[0-9]+\.[0-9]+'
fetch.git = 'https://github.com/emilk/egui.git'

[fcitx5-nord]
src.git = 'https://github.com/tonyfettes/fcitx5-nord.git'
fetch.github = 'tonyfettes/fcitx5-nord'

[snack]
src.webpage = 'https://www.speech.kth.se/snack/'
src.regex = 'Snack v[0-9]+\.[0-9]+\.[0-9]+'
src.prefix = 'Snack v'
fetch.url = 'http://www.speech.kth.se/snack/dist/snack$ver.tar.gz'

[supergfxctl]
src.aur = "supergfxctl"
fetch.git = 'https://gitlab.com/asus-linux/supergfxctl'

[wavesurfer]
src.httpheader = 'http://downloads.sourceforge.net/wavesurfer/wavesurfer-1.8.8p5-src.tgz'
src.regex = '[0-9]+.[0-9]+.[0-9]+p[0-9]+'
fetch.url = 'http://downloads.sourceforge.net/wavesurfer/wavesurfer-$ver-src.tgz'

[droidcam-obs-plugin]
src.aur = 'droidcam-obs-plugin'
src.branch = '$ver'
fetch.url = 'https://github.com/dev47apps/droidcam-obs-plugin'

[python-doq]
src.pypi = 'doq'
fetch.pypi = 'doq'
